# -*- coding: utf-8 -*-
"""Explore pandas series

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fv2xGCBMQZdYmMPd6yMyuwq-Wx32JFJy
"""

import pandas as pd

movies = pd.read_csv('http://bit.ly/imdbratings')

movies.head()

movies.dtypes

movies.genre.describe()

movies.genre.value_counts()

movies.genre.value_counts(normalize=True)

type(movies.genre.value_counts())

movies.genre.value_counts().head()

movies

movies.genre.nunique()

pd.crosstab(movies.genre , movies.content_rating)

movies.duration.describe()

movies.duration.mean()

import matplotlib as mp

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

movies.duration.plot(kind='hist')

movies.duration.plot(kind='bar')

movies.genre.value_counts().plot(kind='bar')