# -*- coding: utf-8 -*-
"""missing values  in pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L795h9HJbsCkCaGknGONMW0v7Hc8lXzt
"""

import pandas as pd

ufo = pd.read_csv('http://bit.ly/uforeports')

ufo.tail()

ufo.isnull().tail()

ufo.notnull().tail()

ufo.isnull().sum()

pd.Series([True,False,True,False]).sum()

ufo[ufo.City.isnull()]

ufo.shape

ufo.dropna(how='any').shape

ufo.head()

ufo.shape

ufo.dropna(subset=['City','Shape Reported'], how='all').shape

ufo['Shape Reported'].value_counts(dropna = False)

ufo['Shape Reported'].fillna(value='VARIOUS' , inplace=True)